services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/shopee_db
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:*,http://127.0.0.1:*
    ports:
      - '8080:8080'
    networks:
      - shopee-network
    depends_on:
      - mongodb
      - redis
  mongodb:
    image: mongo:6.0
    ports:
      - '27017:27017'
    networks:
      - shopee-network
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - shopee-network

networks:
  shopee-network:
    driver: bridge

volumes:
  mongodb_data:
