services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - shopee-app:latest
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: shopee-app:latest
    container_name: shopee-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - MONGODB_URI=${MONGODB_URI}
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,http://localhost:*,http://127.0.0.1:*
    networks:
      - shopee-network
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: redis:alpine
    container_name: shopee-redis
    ports:
      - 6379:6379
    networks:
      - shopee-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shopee-network:
    driver: bridge
